<?php $_order = $this->getOrder() ?>
<?php if ($_order): ?>
    <table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
        <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo $this->__('Name') ?></th>
            <th align="left" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo $this->__('Ordered') ?></th>
            <th align="right" bgcolor="#EAEAEA"
                style="font-size:13px; padding:3px 9px"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        </thead>

        <?php $i = 0;
        foreach ($_order->getAllItems() as $_item): ?>
            <?php if ($_item->getParentItem()) continue; else $i++; ?>
            <tbody<?php echo $i % 2 ? '' : ' bgcolor="#F6F6F6"' ?>>
            <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                <?php echo $_item->getName(); ?>
            </td>
            <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                <?php echo $_item->getSku(); ?>
            </td>
            <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                <?php echo (int)$_item->getQtyOrdered(); ?>
            </td>
            <td align="right" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                <?php echo Mage::helper('core')->currency($_item->getBaseRowTotalInclTax(), true, false); ?>
            </td>
            </tbody>
        <?php endforeach; ?>
    </table>
<?php endif; ?>