<?php
$category = $this->getCategory();
$configs = Mage::helper('blog/configs')->getAllConfigs();
?>
<div class="blog-category type-display-<?php echo $category->getType(); ?>">
    <h1 class="title">
        <?php echo $category->getName(); ?>
    </h1>

    <?php
    $categoryImg = $category->getImage();
    if (strlen($categoryImg)):
        ?>
        <div class="image">
            <img src="<?php echo Mage::helper('all')->imageSrc($categoryImg); ?>" title="<?php echo $category->getName(); ?>" width="<?php echo $configs->getBlogCategoryViewImageWidth(); ?>" height="<?php echo $configs->getBlogCategoryViewImageHeight(); ?>"/>
        </div>
        <div class="description">
            <?php echo nl2br($category->getDescription()); ?>
        </div>
    <?php endif; ?>
</div>
<div id="category_article" class="category-article">
    <?php echo $this->getChildHtml('article_list'); ?>
</div>